/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 anchor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/anchor.glb");
  return (
    <group {...props} dispose={null} scale={0.01} position-y={3}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.M_dFF0000_0_0} />
      <mesh
        geometry={nodes.Mesh_1.geometry}
        material={materials.M_d3C3C3C_0_0}
      />
      <mesh
        geometry={nodes.Mesh_2.geometry}
        material={materials.M_d0177A5_0_0}
      />
    </group>
  );
}

useGLTF.preload("/anchor.glb");
